### ISSUE TITLE
Possible to use with another anime game?

### ISSUE THREAD

**Issue by Yumeo0** [IceDynamix/reliquary#13]
I wanted to ask before I try something that isn't possible in the first place.

Would it be possible to use this library with the other anime game just by switching out the ports and generating the code using that games protos?

**Comment by emmachase** [comment]
Seems like there has been some success with this: https://github.com/hashblen/artifactarium

**Comment by Yumeo0** [comment]
I looked at it and idk if I'd call "Implement, but doesn't work" success. I tried getting it to work too and had no success with that either. I just saw that they have an archiver too. I'll see if that one runs.
Edit: It did not work.

**Comment by emmachase** [comment]
Ah, I didn't look too closely. I'm sure it's possible. But clearly requires
more effort to do right.

**Comment by Yumeo0** [comment]
I tried a bit more and now I am getting a hopefully fixable error. It just complains that there is no key for the current game version as far as I understand. So maybe it can work if I find a key for 5.1?

**Comment by FichteFoll** [comment]
stardb-exporter has keys: <https://github.com/juliuskreutz/stardb-exporter/blob/master/keys/gi.json>

That said, you may also need updated protobuf definitions and I don't know if someone has made the effort yet.

**Comment by Yumeo0** [comment]
> stardb-exporter has keys: https://github.com/juliuskreutz/stardb-exporter/blob/master/keys/gi.json
> 
> That said, you may also need updated protobuf definitions and I don't know if someone has made the effort yet.

Thanks you so much. I didn't know that program had gi code too. I made it work with a bit of inspiration from that code. Big w. So in the end artifactarium did work just the keys were outdated.

**Comment by FichteFoll** [comment]
@Yumeo0 Can you share what you did / how to make it work?

**Comment by Yumeo0** [comment]
> @Yumeo0 Can you share what you did / how to make it work?

I'll post the link to the code here when I clean it up a bit. Give me like a day or two max.

**Comment by Yumeo0** [comment]
@FichteFoll
https://gitlab.yumeo.dev/yumeo/mualani-guide

Rust code is in the src-tauri folder. You need to put the [gi.json](https://github.com/juliuskreutz/stardb-exporter/blob/master/keys/gi.json) in the public folder and rename it to keys.json. Rest of the steps to run it are in the readme.

If you want more protos than what I compiled you need to find them or dump them yourself. But I think I got the most important ones in there already. Also if you know how to dump protos or have some more then hit me up :D

**Comment by FichteFoll** [comment]
Thanks for that. I had to make some adjustments, so I'm writing them down here:

1. I had to rename `proto_gen/build.rs` because it was attempting to build the proto rs files without the original proto definitions in the repo, but since the built ones are in there already I didn't need to run the build steps anyway.
2. Listing devices in `main.rs` failed because some didn't have a description and you used `unwrap` on them. I replaced that with `device.desc.unwrap_or("No description".to_owned())`.
3. (Just an FYI) vite warns about `#` characters in the path and it does indeed break the UI, so I had to move the repo to a path without that.
4. As per usual (same for reliquary-archiver), you need to `sudo setcap CAP_NET_RAW=+ep src-tauri/target/debug/mualani_guide` after each build on Linux before you can read network traffic. Could also run as root but I'd rather not. Also note that despite the following error on console, the UI did show  "Capture started successfully".
```
thread '<unnamed>' panicked at src/sniffer.rs:39:18:
Failed to start packet capture: PcapError("socket: Operation not permitted")
```

After all that, I got a log for `PlayerTokenRsp`, indicating that the setup works. Unfortunately I only then noticed that the artifcat scanner hasn't actually been implemented 😅, but this is already a huge step in the right direction. I personally don't have the time to do this even though I would like to, so I hope you'll be able to work that out eventually.

I also personally don't see a need for a GUI for a tool like this, so I'd be fine with a CLI only, but when you start adding optimizer functionality, I understand why you'd want to have this. However, we already have an optimizer and we don't have an artifact sniffer, so my priority would definitely lie there first. 😉

**Comment by Yumeo0** [comment]
@FichteFoll thanks for all the feedback. I will try and fix everything you wrote here. Thing is I use windows so I didn't really test linux at all.

I'll work on the artifact scanner today though and see how far I get.

Also I made a mirror of my gitlab repo on github so we can move convos over there https://github.com/Yumeo0/Mualani-Guide

**Comment by Yumeo0** [comment]
@FichteFoll alright last message on IceDynamix's repo for real. I made an issue and a branch that should have your "Operation not permitted" error fixed. I'd appreciate if you can tell me if it actually works.
https://github.com/Yumeo0/Mualani-Guide/issues/1
